### ISSUE TITLE
foundthings db

### ISSUE THREAD

**Issue by bbartling** [JoelBender/bacpypes-snapshot#1]
I ran the script on our office test bench HVAC system with the README tips that creates the `foundthings` db.

Is this SQLite?

Actually through my sqlite db browser I can access the `foundthings`  by going through `All files`
![image](https://user-images.githubusercontent.com/29737117/132573121-ce1cbd6b-4156-4be0-969d-cb65747a23e2.png)

And there is data in it, like 15 MB. 
![image](https://user-images.githubusercontent.com/29737117/132573225-5873055c-1982-4431-8a9c-538a9f96db1a.png)

![image](https://user-images.githubusercontent.com/29737117/132573267-6579d64a-7954-49cf-9728-a493e8b5dc12.png)

Is it possible to retrieve point names in addition to the other information when running the script?

![image](https://user-images.githubusercontent.com/29737117/132572845-57dfbd20-07e1-47e2-ac5e-01ac693aa14a.png)

**Comment by JoelBender** [comment]
Yes, it's a SQLite database.  The `value` column is the Python serialization of the BACnet value using [pickle](https://docs.python.org/3/library/pickle.html) because some of the values are arrays and/or have embedded structures.  The **dump** application in the project will translate those values back into some kind of printable string, but you will lose the distinction between integer and unsigned and character strings will lose their encodings.  Normally that's not a huge problem, it's only when re-presenting the values back over BACnet that it makes a difference.

Notice that the property identifiers that are integers are in the "vendor extended range" so you can still dump the value but you will not have any way of knowing what that means without documentation from the vendor.

**Comment by JoelBender** [comment]
It's cool that you got it working on Windows, I haven't seen that before.

**Comment by bbartling** [comment]
Hi Joel,

The Windows aspect is just something I have to work with because its the only machine I could get my hands on at the moment I am tinkering around with Ubuntu 20.04 too.


Could I ever bug you about the bacpypes samples `ReadObjectList.py`? That script it pretty much exactly what I was hoping to find in my IoT role which is a bit of a new venture for me. I pasted in the code buttered up a portion of the code to incorporate the results into a Pandas dataframe where Pandas has an easy button to save data to sqlite which is nice for newbie programmers.

What I like about this at least for what I am hoping to do with IoT and smart building to smart grid control is to be able to look up a "point" by name from sqlite and find the point ID, point Type, as well as controller bacnet instance ID.

This is a screenshot of the pandas dataframe:
![image](https://user-images.githubusercontent.com/29737117/132710008-fb4721ea-0e91-47d4-b8d6-f6703c4c87b4.png)


Does this method seem silly to you at all? For my purposes of adjusting setpoints up and down on the HVAC system for smart grid needs its all I need. I definitely understand too a lot of research needs to be done up front on the point names of devices to make sure the IoT person is adjusting the correct setpoint : )


Could something like this ever be rolled up into an automated process where with `bacpypes-snapshot` the process of auto discovering a range of devices is super cool. Thanks for anytime you have in reading and responding.

```
#!/usr/bin/env python

"""
This application is given the device instance number of a device and its
address read the object list, then for each object, read the object name.
"""

from collections import deque
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

from bacpypes.debugging import bacpypes_debugging, ModuleLogger
from bacpypes.consolelogging import ConfigArgumentParser

from bacpypes.core import run, deferred, stop
from bacpypes.iocb import IOCB

from bacpypes.primitivedata import ObjectIdentifier, CharacterString
from bacpypes.constructeddata import ArrayOf

from bacpypes.pdu import Address
from bacpypes.apdu import ReadPropertyRequest, ReadPropertyACK

from bacpypes.app import BIPSimpleApplication
from bacpypes.local.device import LocalDeviceObject

# some debugging
_debug = 0
_log = ModuleLogger(globals())

# globals
this_device = None
this_application = None

# convenience definition
ArrayOfObjectIdentifier = ArrayOf(ObjectIdentifier)

#
#   ObjectListContext
#

class ObjectListContext:

    def __init__(self, device_id, device_addr):
        self.device_id = device_id
        self.device_addr = device_addr

        self.object_list = []
        self.object_names = []

        self._object_list_queue = None

    def completed(self, had_error=None):
        if had_error:
            print("had error: %r" % (had_error,))
        else:
        
            object_type = []
            object_id = []
            
            for objid, objname in zip(self.object_list, self.object_names):
                print("%s: %s" % (objid, objname))
                object_type.append(objid[0])
                object_id.append(objid[1])
                

            df = pd.DataFrame({'object_names': self.object_names,'object_type': object_type,'object_id': object_id})
            df['device_id'] = pd.Series([self.device_id[1] for x in range(len(df.index))])
            print(df)
            

            engine = create_engine('sqlite:///all_bacnet_bas.db', echo=True)
            sqlite_connection = engine.connect()
            sqlite_table = "all_data"
            df.to_sql(sqlite_table, sqlite_connection, if_exists='append')
            sqlite_connection.close()
            print("Data saved to sql!")

            
            
        stop()



#
#   ReadObjectListApplication
#

@bacpypes_debugging
class ReadObjectListApplication(BIPSimpleApplication):

    def __init__(self, *args):
        if _debug: ReadObjectListApplication._debug("__init__ %r", args)
        BIPSimpleApplication.__init__(self, *args)

    def read_object_list(self, device_id, device_addr):
        if _debug: ReadObjectListApplication._debug("read_object_list %r %r", device_id, device_addr)

        # create a context to hold the results
        context = ObjectListContext(device_id, device_addr)

        # build a request for the object name
        request = ReadPropertyRequest(
            destination=context.device_addr,
            objectIdentifier=context.device_id,
            propertyIdentifier='objectList',
            )
        if _debug: ReadObjectListApplication._debug("    - request: %r", request)

        # make an IOCB, reference the context
        iocb = IOCB(request)
        iocb.context = context
        if _debug: ReadObjectListApplication._debug("    - iocb: %r", iocb)

        # let us know when its complete
        iocb.add_callback(self.object_list_results)

        # give it to the application
        self.request_io(iocb)

    def object_list_results(self, iocb):
        if _debug: ReadObjectListApplication._debug("object_list_results %r", iocb)

        # extract the context
        context = iocb.context

        # do something for error/reject/abort
        if iocb.ioError:
            context.completed(iocb.ioError)
            return

        # do something for success
        apdu = iocb.ioResponse

        # should be an ack
        if not isinstance(apdu, ReadPropertyACK):
            if _debug: ReadObjectListApplication._debug("    - not an ack")
            context.completed(RuntimeError("read property ack expected"))
            return

        # pull out the content
        object_list = apdu.propertyValue.cast_out(ArrayOfObjectIdentifier)
        if _debug: ReadObjectListApplication._debug("    - object_list: %r", object_list)

        # store it in the context
        context.object_list = object_list

        # make a queue of the identifiers to read, start reading them
        context._object_list_queue = deque(object_list)
        deferred(self.read_next_object, context)

    def read_next_object(self, context):
        if _debug: ReadObjectListApplication._debug("read_next_object %r", context)

        # if there's nothing more to do, we're done
        if not context._object_list_queue:
            if _debug: ReadObjectListApplication._debug("    - all done")
            context.completed()
            return

        # pop off the next object identifier
        object_id = context._object_list_queue.popleft()
        if _debug: ReadObjectListApplication._debug("    - object_id: %r", object_id)

        # build a request for the object name
        request = ReadPropertyRequest(
            destination=context.device_addr,
            objectIdentifier=object_id,
            propertyIdentifier='objectName',
            )
        if _debug: ReadObjectListApplication._debug("    - request: %r", request)

        # make an IOCB, reference the context
        iocb = IOCB(request)
        iocb.context = context
        if _debug: ReadObjectListApplication._debug("    - iocb: %r", iocb)

        # let us know when its complete
        iocb.add_callback(self.object_name_results)

        # give it to the application
        self.request_io(iocb)

    def object_name_results(self, iocb):
        if _debug: ReadObjectListApplication._debug("object_name_results %r", iocb)

        # extract the context
        context = iocb.context

        # do something for error/reject/abort
        if iocb.ioError:
            context.completed(iocb.ioError)
            return

        # do something for success
        apdu = iocb.ioResponse

        # should be an ack
        if not isinstance(apdu, ReadPropertyACK):
            if _debug: ReadObjectListApplication._debug("    - not an ack")
            context.completed(RuntimeError("read property ack expected"))
            return

        # pull out the name
        object_name = apdu.propertyValue.cast_out(CharacterString)
        if _debug: ReadObjectListApplication._debug("    - object_name: %r", object_name)

        # store it in the context
        context.object_names.append(object_name)

        # read the next one
        deferred(self.read_next_object, context)

#
#   __main__
#

def main():
    global this_device
    global this_application

    # parse the command line arguments
    parser = ConfigArgumentParser(description=__doc__)

    # add an argument for interval
    parser.add_argument('device_id', type=int,
          help='device identifier',
          )

    # add an argument for interval
    parser.add_argument('device_addr', type=str,
          help='device address',
          )

    # parse the args
    args = parser.parse_args()

    if _debug: _log.debug("initialization")
    if _debug: _log.debug("    - args: %r", args)

    # make a device object
    this_device = LocalDeviceObject(ini=args.ini)
    if _debug: _log.debug("    - this_device: %r", this_device)

    # make a simple application
    this_application = ReadObjectListApplication(this_device, args.ini.address)

    # build a device object identifier
    device_id = ('device', args.device_id)

    # translate the address
    device_addr = Address(args.device_addr)

    # kick off the process after the core is up and running
    deferred(this_application.read_object_list, device_id, device_addr)

    _log.debug("running")

    run()

    _log.debug("fini")

if __name__ == "__main__":
    main()
```

**Comment by bbartling** [comment]
Whoop accidently closed it. DIdnt mean to do that....

**Comment by bbartling** [comment]
Hey Joel,

Curious to ask your opinion on this, my HVAC field technician for building automation controls brain is capable of hacking together code to-do-things.

Could a similar process be rolled into this bacpypes-snapshot project? My idea is sort of an implementation process for IoT which I am hoping I can use this for. So basically the IoT person can run this when trying to understand the BAS prior to setting up the IoT platform and control sequences for the HVAC.

So this is the only way I know how to do things, I apologize this maybe asking a lot but would you have any tips for how to do things better?

I can do a bacnet whois with BAC0, save the results to a data structure and then use the `os` to run the bacpypes `ReadObjectList.py` for each device_id and address found from the BAC0 whois. The `ReadObjectList.py` has the pandas process for saving the results to an sqlite database. Ultimately I have some idea in mind for the IoT platform to use this data base to find all zone temperatures, or zone temperature setpoints, or discharge air temperatures, etc.


```
import BAC0, time
import glob, os

bacnet = BAC0.lite()


#scan network
time.sleep(1)
devices = bacnet.whois(global_broadcast=True)
device_mapping = {}
for device in devices:
    if isinstance(device, tuple):
        device_mapping[device[1]] = device[0]
        print("Detected device %s with address %s" % (str(device[1]), str(device[0])))
print(device_mapping)
print((str(len(device_mapping)) + " devices discovered on network."))

# shut down BAC0 so we can use bacpypes
bacnet.disconnect()
time.sleep(5)

add_port_device_mapping = {}
for device_id,address in device_mapping.items():
    if address.count('.') == 3:
        add_port_device_mapping[device_id] = f'{address}:47808'
    else:
        add_port_device_mapping[device_id] = address
print(add_port_device_mapping)


try:
    # py -3.9 ReadObjectList.py 1002 10.200.200.32:47808
    # in Windows terminal to run the .py file
    for device_id,address in add_port_device_mapping.items():
        
        os.system(f'py -3.9 ReadObjectList.py {device_id} {address}')
        print(f'ran {device_id} {address} sucessful')
        time.sleep(300)

except KeyboardInterrupt:
    pass

finally:
    print("Done deal...")
```

Thanks for anytime you have in response.

**Comment by JoelBender** [comment]
BACpypes itself can do the Who-Is part, BAC0 as an application is using it in the background.  So it sounds like you would like a version of BAC0 that also does something a little different than what it is doing now, so I think this discussion should be moved over there and work with Christian on improving it.  I'll tag him and see what he thinks.

**Comment by ChristianTremblay** [comment]
Everything could be done inside BAC0 as you can always trigger "kinda" direct bacpypes commands...


Using
```
objlst = bacnet.read("2:4 device 5000 objectList")
```

will get you the object list of a device in network 2, address 4 device id 5000
Address could also be an IP address (ex. 192.168.1.10 instead of 2:4)

You could also use all the devices found in the Whois (or `bacnet.discover()`and declare BAC0.device for each of them. This way you will get points names, descriptions, unit, etc. Just specify `poll=0` so you won't trigger the polling feature as you don't need it. 

Once the devices are created you will be able to write to them using `device[pointname]=value` which is easy. 

I must go now but if you want you can poke me and we'll see what can be done to help figure out a way of doing what you need.

**Comment by bbartling** [comment]
Thanks Christian!
